// Esto nos sirve capturar errores en el c贸digo. Es decir se pude aplicar a una parte
// del c贸digo para arrojar un mensaje al usuario cuando se produzca un  error
// dentro del "try" se mete el c贸digo susceptible a fallo
try {
    let year = 2019;
    alert(yea);
} catch (error) { console.log('Ha ocurrido un error en el c贸digo') };